### ISSUE TITLE
Hello, What is the default username and password?

### ISSUE THREAD

**Issue by KingsVolvo** [ai-dock/invokeai#1]
I started the docker and open the portal, but don`t know how to login the portal. 
How to get throught the verification? thanks~

**Comment by robballantyne** [comment]
It's `user`/`password` though you can change it with the environment variables `WEB_USER` and `WEB_PASSWORD`

More info at https://github.com/ai-dock/base-image/wiki/2.0-Environment-Variables#all-containers though it does need updating

**Comment by KingsVolvo** [comment]
Oh , I see.  Thanks very much~
